

################################### Italian language #####################################
[it]
languageName = "It"
languageCode = "it-it"
contentDir = "content/italian"
weight = 1

[it.params]
home = "Home"
# footer content
footer_content = "Fai rendere il tuo immobile veramente con professionisti degli affitti brevi qualificati"
# copyright
copyright = "Made with ❤️ By [Stay Tips](https://stay.tips/)"

################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2

[en.params]
home = "Home"
# footer content
footer_content = "Make your property truly make it with qualified short rental professionals"
# copyright
copyright = "Designed & Developed By [Stay Tips](https://stay.tips/)"

# navigation button (English label)
[en.params.navigation_button]
enable = true
label = "Empty property?"
link = "contact/"
